config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'recover_password',
    confirmation: 'email_confirmation',
    registration: 'register',
    unlock: 'unlock_account'
  }
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'my_stock',to:'pages#my_stock'
  get 'search_stock',to:'stocks#search'
  get 'my_friends',to:'pages#my_friends'
  delete 'my_friends',to:"pages#delete_friends"
  get 'search_friends',to:'pages#search_friends'
  post 'add_friend/:id',to:'pages#add_friend',as:"add_friend"
  get 'users/:id',to:"pages#show",as:"user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend,class_name:'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many:user_stocks
    has_many:users,through: :user_stocks
    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex[:pub_key],
            secret_token: Rails.application.credentials.iex[:sec_key],
            endpoint: 'https://cloud.iexapis.com/v1'
        )
        begin
            Stock.new(ticker:ticker_symbol,name:client.company(ticker_symbol).company_name,last_price:client.price(ticker_symbol))
        rescue
            return nil
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many:user_stocks
  has_many:stocks,through: :user_stocks
  has_many:friendships
  has_many:friends,through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def reject_current(users)
    users.reject{ |user| user.id == self.id}
    return users
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
    belongs_to:user
    belongs_to:stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action:authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def after_sign_in_path_for(resource)
    # Redirect regular users to their profile page
    about_path
  end

  def after_sign_out_path_for(resource_or_scope)
    # Customize the redirect path after sign out
    # For example, redirect to the home page
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home

  end

  def about
  
  end
  
  def my_stock
    @traked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def delete_friends
    # byebug
    @friend = Friendship.find_by(user_id:current_user,friend_id:params[:id])
    if @friend.destroy
      redirect_to my_friends_path
    end
  end

  def search_friends
    if params[:friend].present?
      @friend = User.where("first_name LIKE ? AND id != ? ","%#{params[:friend]}%",current_user.id).all
      # @friend = current_user.reject_current(@friend)
      if @friend
        respond_to do |format|
          format.js { render partial: 'pages/friend'}
      end
      else
        flash.now[:alert] = "Enter The Valid Users"
        respond_to do |format|
          format.js { render partial: 'pages/friend'}
        end
      end
    else
      flash.now[:alert] = "Enter The User Name"
      respond_to do |format|
        format.js { render partial: 'pages/friend'}
      end
    end
  end

  def add_friend
    # byebug
    current_user.friends << User.find(params[:id])
    redirect_to my_friends_path
  end

  def show
    # byebug
    @user = User.find(params[:id])
    @traked_stocks = @user.stocks
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        # byebug
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                respond_to do |format|
                    format.js { render partial: 'pages/result'}
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Please Enter The Correct Symbol"
                    format.js { render partial:'pages/result'}
                end
            end
        else
            respond_to do |format|
                flash.now[:alert] = "Please Enter The Symbol"
                format.js { render partial:'pages/result'}
            end
        end
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        # byebug
        @stock = Stock.where(ticker:params[:stock]).first
        if !@stock
            @stock = Stock.new_lookup(params[:stock])
            @stock.save
        end
        current_user.stocks << @stock
        redirect_to my_stock_path
    end

    def destroy
        @stock = current_user.stocks.where(id:params[:id]).first
        if @stock.destroy
            redirect_to my_stock_path
        else
            flash[:notice] = "Not Deleted"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/layouts/_message.html.erb
<% if notice %>
    <p><%= notice %></p>
<% end %>

<% if alert %>
    <p><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTraker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/message' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_friend.html.erb
<div>
    <%= render 'layouts/message' %>
</div>
<% if @friend %>
    <% @friend.each do |fri| %>
        <p><%= fri.first_name %></p>
        <p><%= fri.last_name %></p>
        <p><%= fri.email %></p>
        <%= link_to "View Profile",user_path(fri.id) %>
        <% if !(current_user.friends.where(id:fri.id).exists?) %>
            <%= link_to "Add Friend",add_friend_path(fri.id),method: :post %>
        <% else %>
            <p>You Are Already Friends</p>
        <% end %>
    <% end %>
<% end %>

app/views/pages/_friend.js.erb
document.querySelector('#result').innerHTML = '<%= j render 'pages/friend.html' %>'

app/views/pages/_result.html.erb
<div>
    <%= render 'layouts/message' %>
</div>
<% if @stock %>
    <p><%= @stock.ticker %></p>
    <p><%= @stock.name %></p>
    <p><%= @stock.last_price %></p>
    <% if !(current_user.stocks.where(ticker:@stock.ticker).exists?) && current_user.stocks.count < 10 %>  
        <%= link_to "Add",user_stocks_path(user:current_user,stock:@stock.ticker),method: :post %>
    <% else %>
        <p>You Are Already Tracking</p>
    <% end %>
<% end %>

app/views/pages/_result.js.erb
document.querySelector('#result').innerHTML = '<%= j render 'pages/result.html' %>'

app/views/pages/about.html.erb
<h1>Inish</h1>
<%= button_to 'Sign out', destroy_user_session_path, method: :delete %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/my_friends.html.erb
<%= form_tag search_friends_path,remote:true,method: :get do %>
    <%= text_field_tag :friend,params[:friend] %>
    <%= button_tag type: :submit do %>
        Search
    <% end %>
<% end %>

<div id="result">

</div>

<% if @friends %>
    <% @friends.each do |friend| %>
        <div>
            <p>Email : <%= friend.email %>  First Name : <%= friend.first_name %>  Last Name : <%= friend.last_name %> <%= link_to "Stop Following",my_friends_path(id:friend.id),method: :delete,data:{confirm:"Are You Sure?"} %></p>
        </div>
    <% end %>
<% end %>

app/views/pages/my_stock.html.erb
<h1>Search Stock</h1>
<%= form_tag search_stock_path,remote: true,method: :get do %>
    <%= text_field_tag :stock,params[:stock] %>
    <%= button_tag type: :submit do %>
        Search
    <% end %>
<% end %>
<div id="result">

</div>

<% @traked_stocks.each do |stock| %>
    <div>
        <p>Ticker : <%= stock.ticker %>  Name : <%= stock.name %>  Price : <%= stock.last_price %> <%= link_to "Remove", user_stock_path(stock),method: :delete,data:{confirm:"Are You Sure?"} %></p>
    </div>
<% end %>

app/views/pages/show.html.erb
<p>Email : <%= @user.email %> <br><br>  First Name : <%= @user.first_name %> <br><br> Last Name : <%= @user.last_name %></p>
<% @traked_stocks.each do |stock| %>
    <div>
        <p>Ticker : <%= stock.ticker %>  Name : <%= stock.name %>  Price : <%= stock.last_price %> 
            <% if @user.id == current_user.id %>
                <%= link_to "Remove", user_stock_path(stock),method: :delete,data:{confirm:"Are You Sure?"} %></p>
            <% elsif !(current_user.stocks.where(id:stock.id).exists?) && current_user.stocks.count < 10 %>
                <%= link_to "Add",user_stocks_path(user:current_user,stock:stock.ticker),method: :post %>
            <% else %>
                <p>You Are Already Tracking</p>
            <% end %>
    </div>
<% end %>